export const mockdata = [
  {
    id: 1,
    package_name: "OneMOneC",
    package_type: "Monthly",
    package_year: 0,
    package_month: 1,
    package_date: 0,
    package_class: 1,
    package_price: 159,
    package_all: 7,
    package_status: false,
    package_status_view: false,
  },
  {
    id: 2,
    package_name: "OneYThreeC",
    package_type: "Yearly",
    package_year: 1,
    package_month:0,
    package_date: 0,
    package_class: 3,
    package_price: 859,
    package_all: 8,
    package_status: true,
    package_status_view: true,
  },
  {
    id: 3,
    package_name: "OneYSixC",
    package_type: "Yearly",
    package_year: 1,
    package_month: 0,
    package_date: 0,
    package_class: 6,
    package_price: 999,
    package_all: 12,
    package_status: false,
    package_status_view: false,
  },
  {
    id: 4,
    package_name: "OneMSixC",
    package_type: "Monthly",
    package_year: 0,
    package_month: 1,
    package_date: 0,
    package_class: 6,
    package_price: 459,
    package_all: 12,
    package_status: false,
    package_status_view: false,
  },
  {
    id: 5,
    package_name: "ThreeMFourC",
    package_type: "Monthly",
    package_year: 0,
    package_month: 1,
    package_date: 0,
    package_class: 4,
    package_price: 699,
    package_all: 6,
    package_status: false,
    package_status_view: false,
  },
  {
    id: 6,
    package_name: "FourMTwoC",
    package_type: "Monthly",
    package_year: 0,
    package_month: 1,
    package_date: 0,
    package_class: 2,
    package_price: 679,
    package_all: 4,
    package_status: false,
    package_status_view: false,
  },
  {
    id: 7,
    package_name: "FourMOneC",
    package_type: "Monthly",
    package_year: 1,
    package_month: 1,
    package_date:0,
    package_class: 1,
    package_price: 599,
    package_all: 3,
    package_status: false,
    package_status_view: false,
  },
  {
    id: 8,
    package_name: "Custom01",
    package_type: "Custom",
    package_year: 0,
    package_month: 1,
    package_date: 15,
    package_class: 4,
    package_price: 359,
    package_all: 1,
    package_status: true,
    package_status_view: true,
  },
  {
    id: 9,
    package_name: "SixMTwoC",
    package_type: "Monthly",
    package_year: 0,
    package_month: 1,
    package_date: 0,
    package_class: 2,
    package_price: 759,
    package_all: 5,
    package_status: false,
    package_status_view: true,
  },
  {
    id: 10,
    package_name: "SixMOneC",
    package_type: "Monthly",
    package_year: 0,
    package_month: 1,
    package_date: 0,
    package_class: 1,
    package_price: 659,
    package_all: 2,
    package_status: true,
    package_status_view: false,
  },
];
